docs: add the bundling instruction for Webpack
pinojs/pino pull request #1236
Opened 2021-11-21 15:04 UTC by pan93412

2021-11-21 15:31 UTC, jsumners requested changes

2021-11-21 15:31 UTC, jsumners commented on docs/bundling.md
>  In particular, a bundler must ensure that the following files are also bundle separately:
You have interrupted a continuous thought/explanation. The new documentation should be subsequent to the current documentation.

2021-11-21 15:35 UTC, jsumners approved these changes

2021-11-22 07:58 UTC, mcollina approved these changes
lgtm

2021-11-22 07:58 UTC, merged