Add option `mixinMergeStrategy`
pinojs/pino pull request #1328
Opened 2022-02-10 09:12 UTC by alexpts

Added new option `mixinMergeStrategy` for define custom strategy merge `mergeObject` from log method argument and `mixin`

Example:
```js
// Custom muttable strategy, `mixin` has priority
const logger = pino({
    mixin() {
        return { tag: 'k8s' }
    },
    mixinMergeStrategy(mergeObject, mixinObject) {
        return Object.assign(mergeObject, mixinObject)
    }
})
logger.info({
    tag: 'local'
}, 'Message')
// {"level":30,"time":1591195061437,"pid":16012,"hostname":"x","tag":"k8s","msg":"Message"}
```

2022-02-10 09:15 UTC, mcollina approved these changes
lgtm

2022-02-10 09:15 UTC, mcollina commented
Why is this needed?

2022-02-14 12:16 UTC, alexpts commented
Everything is fine?

2022-02-14 14:40 UTC, jsumners requested changes

2022-02-14 16:02 UTC, alexpts commented on docs/api.md
> +the second parameter is the value on result of `mixin()` (* See [`mixin` option](#opt-mixin) or an empty object.
fixed

2022-02-14 16:06 UTC, alexpts commented
@jsumners I changed docs and add jsdoc

2022-02-14 17:00 UTC, jsumners commented on lib/proto.js
> + */
```suggestion
/**
 * Default strategy for creating `mergeObject` from arguments and the result from `mixin()`.
 * Fields from `mergeObject` have higher priority in this strategy.
 *
 * @param {Object} mergeObject The object a user has supplied to the
 * logging function.
 * @param {Object} mixinObject The result of the `mixin` method.
 * @return {Object}
 */
```

2022-02-14 17:25 UTC, alexpts commented on lib/proto.js
> + */
Fixed

2022-02-14 20:59 UTC, merged

2022-02-15 06:28 UTC, alexpts commented
Thanks!

2022-02-15 11:10 UTC, mcollina commented
I just noticed this was done on the v6.x branch and not against `master`. This is not ok as it takes significant amount from time for us to add it to `master` too. I'll try to do the work now but we should really be updating our CONTRIBUTING docs.

2022-02-15 11:33 UTC, mcollina commented
After spending 30 minutes trying to make some sense of this in the master branch, I have decided to revert the change on the v6.x line. Please send a fresh PR to master and we'll talk about the problem of this design there. We should probably rethink the mixin concept.

2022-02-15 12:28 UTC, alexpts commented
I will prepare new PR for master. But i need it for v6.x also