Fix hasOwnProperty usage
pinojs/pino pull request #1359
Opened 2022-03-04 19:04 UTC by joshkel

Under certain circumstances, the user's mergingObject may be passed through as is to `write`. If the mergingObject was created with no prototype (`Object.create(null)`), then calling hasOwnProperty will fail.

Sample problematic code:

```js
const PinoMS = require('pino-multi-stream');
const pino = require('pino');
const logger = pino({}, pino.multistream([
  { stream: PinoMS.prettyStream({ prettyPrint: { colorize: true, translateTime: 'SYS:standard' } }) }
]));

const example = Object.create(null);
Object.assign(example, { hello: 'world' });
logger.info(example, 'hello world');
```

(This worked prior to Pino 7.8.0.)

For consistency, I also updated another usage of hasOwnProperty to match the new style.

2022-03-04 20:36 UTC, mcollina requested changes
Good spot! Can you please add a unit test?

2022-03-23 15:47 UTC, joshkel commented
@mcollina Done. I apologize for the delay.

2022-03-23 15:59 UTC, jsumners approved these changes
Looks good to me.

2022-03-23 21:57 UTC, mcollina approved these changes
lgtm

2022-03-23 21:58 UTC, merged