fix(publishing): add preval pino version
pinojs/pino pull request #1453
Opened 2022-06-02 20:25 UTC by budarin

Preval pino version before publishing the package

2022-06-03 12:13 UTC, mcollina commented
the approach we follow in Fastify is slightly different

There is https://github.com/fastify/fastify/blob/c37888c281087089c37b3e24f2d2fa61a3304ce4/package.json#L19 that verifies that the version in meta is the same of package.json.

We manually bump the version by running the update script (no prepare step).

2022-06-03 19:06 UTC, budarin commented
ок,I'll refactor the code

2022-06-04 07:49 UTC, mcollina requested changes
Please take a look at how it's done in Fastify. This is still far from it.

There is no package.json script but a test to verify if the meta version number has been bumped.

2022-06-04 07:49 UTC, mcollina commented on lib/utils/preval-pino-version.js
> +const fs = require('fs')
move this file to the build/ folder

2022-06-05 12:00 UTC, mcollina requested changes
Could you add https://github.com/fastify/fastify/blob/1152a45f433b05b56a9c4206855d1322cecb6e83/package.json#L19

and 

https://github.com/fastify/fastify/blob/main/test/internals/version.test.js

2022-06-05 16:14 UTC, mcollina approved these changes
lgtm, thanks

2022-06-10 02:43 UTC, climba03003 commented on test/internals/version.test.js
> +const fastify = require('../..')()
```suggestion
const pino = require('../..')()
```

2022-06-10 02:43 UTC, climba03003 commented on test/internals/version.test.js
> +  t.equal(fastify.version, json.version)
```suggestion
  t.equal(pino.version, json.version)
```

2022-06-10 13:47 UTC, merged