[Fix] Redact mutates the original object
pinojs/pino pull request #1581
Opened 2022-10-30 17:33 UTC by debadutta98

Hi @mcollina,

This PR Closes #1575 

## Work 

- Change `lib/tools.js`
- Update test case in `test/redact.test.js`
- Use an external library [clonedeep](https://www.npmjs.com/package/lodash.clonedeep) to clone a deep copy of an object

Thank you!! waiting for your response

2022-11-01 08:02 UTC, mcollina requested changes
The whole goal of the redact feature is to not incur in the cost of a full depth clone.

2022-11-01 12:20 UTC, jsumners commented on lib/tools.js
> +const cloneDeep = require('lodash.clonedeep')
In addition to Matteo's comment, we would not pull _any_ lodash dependencies into this project. In particular, the `lodash.*` packages are no longer maintained (last I knew). You should look at https://www.npmjs.com/package/rfdc

2022-11-01 12:32 UTC, kibertoad commented
I'm -1 on this. If redact docs don't mention the mutation, they should, but for perf reasons user should be the one responsible for cloning if they need it, as this is not a common need.

2022-11-01 12:34 UTC, jsumners commented
> I'm -1 on this. If redact docs don't mention the mutation, they should, but for perf reasons user should be the one responsible for cloning if they need it, as this is not a common need.

They do note that the mutation is the core of the optimization. But they also state that the original values should be restored after redaction.

2022-11-01 14:06 UTC, debadutta98 commented
> The whole goal of the redact feature is to not incur in the cost of a full depth clone.

Hi @mcollina, Thanks for your time!

The changes are done successfully and I think this [commit](https://github.com/pinojs/pino/pull/1581/commits/2a50d3e96013f732fcdc460353398a7bacabddfe) meets your expectations

2022-11-02 09:05 UTC, mcollina commented
This is significantly better however it's still cloning everything before redacting. The generic approach of `fast-redact` is to clone in place. It's possible to fix those bugs there.

cc @davidmarkclements

2022-11-02 13:39 UTC, debadutta98 commented
> This is significantly better however it's still cloning everything before redacting. The generic approach of `fast-redact` is to clone in place. It's possible to fix those bugs there.
> 
> cc @davidmarkclements

Is there any alternative idea that you want to recommend here?

2022-11-02 17:59 UTC, davidmarkclements commented
@debadutta98 the bug will need chasing down in fast-redact, PR's definitely welcome as I'm quite time constrained atm but I will get to it at some (potentially distant) point if not

2022-11-02 19:42 UTC, debadutta98 commented
> @debadutta98 the bug will need chasing down in fast-redact, PR's definitely welcome as I'm quite time constrained atm but I will get to it at some (potentially distant) point if not

sure, i will

2023-04-01 14:58 UTC, closed without merging