Add default levels to opts in multistream
pinojs/pino pull request #1760
Opened 2023-07-30 04:25 UTC by tzviki

2023-07-31 08:04 UTC, mcollina requested changes

2023-08-01 08:28 UTC, mcollina approved these changes
lgtm

2023-08-01 11:42 UTC, jsumners approved these changes
Looks good to me.

2023-08-02 17:10 UTC, mcollina commented
the tests seems to be failing

2023-08-02 23:54 UTC, tzviki commented
I merged in master. Still trying to determine cause of failing tests, but cannot get to the bottom of it yet. Will keep looking

2023-08-03 15:34 UTC, tzviki commented
I'm confused as to why the tests are failing. This might not be too helpful, but trying this on my fork [here](https://github.com/tzviki/pino/actions/runs/5751314759) it fails even without any changes (i.e. a simple pr with a comment added).
The tests pass when I simply try to re-run just the failed tests (sometimes after an attempt or 2).
I have better results when adding a small change to the failing test see [here](https://github.com/tzviki/pino/pull/3/files), but those are still not succeeding on first run (see [here](https://github.com/tzviki/pino/actions/runs/5752619653)).
Happy to continue looking.

2023-08-04 08:00 UTC, mcollina approved these changes
lgtm

2023-08-04 09:21 UTC, merged