Correct type of `pino`'s `stream` parameter
pinojs/pino pull request #1874
Opened 2024-01-03 18:33 UTC by quisido

The second parameter of the `pino` function can be set to `undefined`. This is relevant when dependency injecting a stream:

```ts
function create(stream: DestinationStream | undefined): Logger {
  return pino({ level: 'debug' }, stream);
}
```

This allows me to use `create(undefined)` for default behavior (stdio), but also `create({ write: jest.fn() })` for mocked behavior in unit tests, _without creating a new branch_.

With the definition prior to this PR, the following code is required:

```ts
function create(stream: DestinationStream | undefined): Logger {
  if (typeof stream === 'undefined') {
    return pino({ level: 'debug' });
  }
  return pino({ level: 'debug' }, stream);
}
```

This creates an unnecessary code branch ("What happens when the stream is undefined?") that isn't necessary, as it's the same runtime behavior as the first implementation.

2024-01-03 22:00 UTC, mcollina requested changes
Can you add a test with `tsd`?

2024-01-23 22:58 UTC, quisido commented
Sorry for the delay. I've added it. 👍

2024-01-25 12:32 UTC, mcollina approved these changes
lgtm

2024-01-27 10:02 UTC, quisido commented
Is it possible to re-run the failed test? I think it timed out.

2024-01-27 22:46 UTC, merged