Fix deprecated dependency notation
pinojs/pino pull request #1929
Opened 2024-03-22 19:14 UTC by mbtools

Minor change to replaces a semver v1 notation (with leading `v`) with semver v2.

PS: The npm semver package most likely will deprecate semver v1 support in next major.

2024-03-30 09:16 UTC, mcollina requested changes
good catch! I think it should be a caret.

2024-03-30 09:16 UTC, mcollina commented on package.json
> +    "pino-abstract-transport": "1.1.0",
```suggestion
    "pino-abstract-transport": "^1.1.0",
```

2024-03-31 11:16 UTC, mbtools commented
Makes sense. Changed

2024-03-31 12:25 UTC, jsumners approved these changes

2024-03-31 13:03 UTC, mcollina approved these changes
lgtm

2024-03-31 13:03 UTC, merged