Update transports.md
pinojs/pino pull request #1993
Opened 2024-06-21 12:20 UTC by Jhon-Mosk

Add pino-telegram-webhook transport for send message to Telegram

2024-06-21 13:16 UTC, mcollina approved these changes
lgtm

2024-06-21 13:43 UTC, jsumners requested changes

2024-06-21 13:43 UTC, jsumners commented on docs/transports.md
> +[pino-telegram-webhook](https://github.com/Jhon-Mosk/pino-telegram-webhook) is a Pino v7+ transport for send message to [Telegram](https://telegram.org/).
```suggestion
[pino-telegram-webhook](https://github.com/Jhon-Mosk/pino-telegram-webhook) is a Pino v7+ transport for sending messages to [Telegram](https://telegram.org/). 
```

2024-06-21 13:43 UTC, jsumners commented on docs/transports.md
> +The extra parameter is optional. Parameters that the method [sendMessage](https://core.telegram.org/bots/api#sendmessage) supports can be passed to it
```suggestion
The `extra` parameter is optional. Parameters that the method [`sendMessage`](https://core.telegram.org/bots/api#sendmessage) supports can be passed to it.
```

2024-06-24 07:20 UTC, Jhon-Mosk commented on docs/transports.md
> +[pino-telegram-webhook](https://github.com/Jhon-Mosk/pino-telegram-webhook) is a Pino v7+ transport for send message to [Telegram](https://telegram.org/).
Done

2024-06-24 07:20 UTC, Jhon-Mosk commented on docs/transports.md
> +The extra parameter is optional. Parameters that the method [sendMessage](https://core.telegram.org/bots/api#sendmessage) supports can be passed to it
Done

2024-06-24 10:51 UTC, jsumners approved these changes

2024-06-24 10:51 UTC, merged