Add asObjectBindingsOnly, allowing write to receive only the bindings as object
pinojs/pino pull request #2051
Opened 2024-09-26 22:34 UTC by segevfiner

This allows to pass the format string and args as
is the underlying console when to keep their
special handling, for when using `write` to only
modify the default way the printing to the console
looks rather than writing to an alternate
destination entirely.

The name of the option and its behavior is obviously open for discussion

Part of #1556

2024-09-28 09:12 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2025-01-30 08:54 UTC, mcollina commented
Can. you add some docs?

2025-01-30 08:55 UTC, segevfiner commented
Can you point me where to add them? Also do consider the naming and the exact semantics of this API, see the issues I opened for what I'm trying to eventually achieve.

2025-01-30 08:59 UTC, mcollina commented
https://github.com/pinojs/pino/blob/main/docs/browser.md

I think the name is ok.

2025-02-04 12:13 UTC, jsumners reviewed
Is this applicable to the core logger?

2025-02-04 13:04 UTC, segevfiner commented
What do you mean? It's a variation of a flag that only exists in the browser version, where the output interface is different.

2025-02-05 15:27 UTC, mcollina approved these changes
lgtm

2025-04-16 11:46 UTC, jsumners approved these changes

2025-04-16 11:46 UTC, merged

2025-07-25 18:54 UTC, Morriz commented
@mcollina has this not been released yet? Its been over 3 months already, but its not available in `9.7.0` it seems.