pass merging object to mixins
pinojs/pino pull request #926
Opened 2020-11-13 18:20 UTC by madelinecameron

Allows for mixins to take in an object and add information contextually. 

For instance, if your `mergingObject` has an `error` key (a [JS Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)), I want to add `{ message: error.message, stack: error.stack }`. This will make mixins more useful or having to pull from higher in the scope.

2020-11-13 18:36 UTC, madelinecameron commented
Will add a test shortly, sorry about that. :)

2020-11-13 21:43 UTC, mcollina requested changes
Can you please add a unit test?

2020-11-13 22:40 UTC, mcollina approved these changes
lgtm

2020-11-13 22:40 UTC, mcollina commented
This is also missing some docs update

2020-11-13 23:00 UTC, madelinecameron commented
Yep, was wondering about that, I'll do that. Thanks!

2020-11-13 23:07 UTC, madelinecameron commented
Took a crack at integrating it to documentation, let me know any feedback. :)

2020-11-13 23:11 UTC, mcollina commented on docs/api.md
> +    mixin({ description }) {
let's name the paramenter `obj`, without destructuring

2020-11-15 13:18 UTC, jsumners approved these changes

2020-11-15 14:25 UTC, merged